planet_name = input("Name of a Planet: ").strip()
sh1 = input("Name of the superhero: ").strip()
superpowers = input("Silly superpower: ").strip()
verb1 = input("Enter a verb: ").strip()
sh2 = input("Another Superhero name: ").strip()
sh3 = input("Another Superhero name: ").strip()
verb2 = input("Enter a verb: ").strip()
place_name = input("Enter a name of a place: ").strip()
noun = input("Enter a noun: ").strip()
verb3 = input("Enter a verb ending with -ing: ").strip()
action_verb = input("Enter a action verb: ").strip()
bird = input("Enter a name of a bird: ")

print(f"In {planet_name}, there lived {sh1}. {sh1} had {superpowers} powers. With {superpowers} like this {sh1} could {verb1} {sh2}. {sh1} wanted to turn {sh3} into a weapon. {sh2} got to know about this and decided to {verb2} {sh1}. {sh1} and {sh2} met at {place_name}. {sh1} came to {place_name} with his {noun}. {sh2} was {verb3} {sh3}, who was {sh1}'s' weapon. {sh1} decided to {action_verb} {sh2} while {sh3} flew away like a {bird}")
